<a href="https://colab.research.google.com/github/neuralsrg/SupervisedLearning/blob/main/Tensorflow/Settings_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip uninstall tensorflow

In [ ]:
!pip install tensorflow===2.3.0

In [ ]:
!pip list

In [ ]:
!pip install --upgrade tensorflow

And after this we have to manage Runtime - Restart runtime

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


# Tensorflow

## Constants

In [ ]:
scalar = tf.constant(7)
# scalar.numpy() - to get the value
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
matrix = tf.constant([[6, 5],
                      [5, 6]], dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[6., 5.],
       [5., 6.]], dtype=float16)>

### Built-in initializations

In [ ]:
z = tf.zeros(shape=[3, 1])
z

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.]], dtype=float32)>

In [ ]:
o = tf.ones(shape=[2, 3])
o

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### NumPy

In [ ]:
import numpy as np

some_matrix = np.random.randn(2, 3)
some_matrix

array([[ 0.44960239, -0.70040744, -1.00977769],
       [-0.47314648,  1.32845872, -0.49393205]])

In [ ]:
# NumPy to Tensorflow

tf_matrix = tf.constant(some_matrix)
tf_matrix

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 0.44960239, -0.70040744, -1.00977769],
       [-0.47314648,  1.32845872, -0.49393205]])>

In [ ]:
# Tensorflow to NumPy

tf_matrix = tf.constant([3., 7., 10.])

tf_matrix.numpy() # or
np.array(tf_matrix)

array([ 3.,  7., 10.], dtype=float32)

**Tensorflow**: by default - *float32*

**NumPy**: by default - *float64*

### Shape, rank, size, squeeze

In [ ]:
matrix = tf.ones(shape=[2, 3, 4])
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 3, 4]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [ ]:
tf.reshape(matrix, shape=[4, 3, -1]).shape

TensorShape([4, 3, 2])

In [ ]:
new_matrix = matrix[..., tf.newaxis]
new_matrix.shape

TensorShape([2, 3, 4, 1])

In [ ]:
new_matrix = tf.expand_dims(matrix, axis=1)
new_matrix.shape

TensorShape([2, 1, 3, 4])

In [ ]:
tf.squeeze(new_matrix).shape

TensorShape([2, 3, 4])

### Random tensors

In [ ]:
r1 = tf.random.Generator.from_seed(123)
tensor = r1.normal(shape=[2, 1])
tensor

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 0.8673864 ],
       [-0.29899067]], dtype=float32)>

### Shuffle

In [ ]:
tensor = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]])
tf.random.shuffle(tensor, seed=32) # different every time 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [ ]:
tensor = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]])
tf.random.set_seed(32)
tf.random.shuffle(tensor, seed=32) # uses both global and operation seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

### Matrix operations

In [ ]:
rnd = tf.random.Generator.from_seed(64)
matrix1 = rnd.normal(shape=[2, 3])
matrix2 = rnd.normal(shape=[3, 2])

In [ ]:
# dot-product

tf.matmul(matrix1, matrix2)
tf.tensordot(matrix1, matrix2, axes=1).shape

TensorShape([2, 2])

In [ ]:
# square, sqrt, log

tf.square(matrix1)
tf.sqrt(matrix1)
tf.math.log(tf.abs(matrix1))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7756038, -0.6637185, -2.730314 ],
       [ 0.366393 , -0.7237602,  0.6078095]], dtype=float32)>

### Cast

In [ ]:
matrix = tf.constant([[1, 2],
                      [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.cast(matrix, dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

### min, max, mean, sum, abs

In [ ]:
matrix = tf.constant(np.random.randint(low=0, high=100, size=[3, 10]), dtype=tf.float16)
matrix

<tf.Tensor: shape=(3, 10), dtype=float16, numpy=
array([[67., 96., 84., 68.,  1., 59., 20.,  3., 58., 13.],
       [66., 34., 36., 47., 57.,  6., 63., 35.,  8.,  3.],
       [34., 23., 36.,  7., 65., 75., 66., 66., 57., 63.]], dtype=float16)>

In [ ]:
dct = {}
dct['min'] = tf.reduce_min(matrix, axis=0, keepdims=True)
dct['max'] = tf.reduce_max(matrix, axis=1, keepdims=True)
dct['mean'] = tf.reduce_mean(matrix, axis=0, keepdims=False)
dct['sum'] = tf.reduce_sum(matrix)
dct['abs'] = tf.abs(matrix)
dct

{'abs': <tf.Tensor: shape=(3, 10), dtype=float16, numpy=
 array([[67., 96., 84., 68.,  1., 59., 20.,  3., 58., 13.],
        [66., 34., 36., 47., 57.,  6., 63., 35.,  8.,  3.],
        [34., 23., 36.,  7., 65., 75., 66., 66., 57., 63.]], dtype=float16)>,
 'max': <tf.Tensor: shape=(3, 1), dtype=float16, numpy=
 array([[96.],
        [66.],
        [75.]], dtype=float16)>,
 'mean': <tf.Tensor: shape=(10,), dtype=float16, numpy=
 array([55.66, 51.  , 52.  , 40.66, 41.  , 46.66, 49.66, 34.66, 41.  ,
        26.33], dtype=float16)>,
 'min': <tf.Tensor: shape=(1, 10), dtype=float16, numpy=array([[34., 23., 36.,  7.,  1.,  6., 20.,  3.,  8.,  3.]], dtype=float16)>,
 'sum': <tf.Tensor: shape=(), dtype=float16, numpy=1316.0>}

### argmax, argmin

In [ ]:
tf.argmax(dct['abs'], axis=1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 0, 5])>

### one-hot encoding

In [ ]:
inds = tf.constant([1, 3, 2])
tf.one_hot(inds, depth=5)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>

## Variables

In [ ]:
var = tf.Variable([1, 2], dtype=tf.int32)
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
var[0].assign(8)
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 2], dtype=int32)>

In [ ]:
var.assign_add([10, 10])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([18, 12], dtype=int32)>

## @tf.function

In [ ]:
@tf.function # speeds up the process
def some_function(x, y):
  return tf.matmul(x, y)

# Google Colab

### uploading files 

We can upload any file using google colab files and then read via io.BytesIO

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import io
A_train = np.loadtxt(io.BytesIO(uploaded["file.csv"]), delimiter=',', ndmin=2)

We can also mount Google Drive and read files from there

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# to read from google drive we use path:
# /content/drive/My Drive/...

# We can create loval file and copy it on Google Drive

with open('example.txt', 'w') as f:
  f.write('some content')

# copying
!cp -r "/content/some_dir" "/content/drive/My Drive/other_dir"

### downloading files

In [ ]:
from google.colab import files

with open('example.txt', 'w') as f:
  f.write('some content')

files.download('example.txt') # will download to PC

## GPU 

Runtime -> Change Runtime Type -> Select GPU (Google Colab)

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
!nvidia-smi

Tue Jun 28 12:14:22 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Tensorboard

In [ ]:
%load_ext tensorboard
%tensorboard --logdir /content/other_dir